echo "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKo;:clkXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMWKkookNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO,.;ddc,,dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMNkl:::..oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx..:O0K0k:.lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MM0;.ck00l.;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKl.'oOK0000o.,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MK;.c0000o.'0MMMMMMMMMMMMMMW0dodkXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXd'.ck000000k,.lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "Mk..dK000d..xWMMMMMMMMMMMW0:'':c,;kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOxdollodkKWMMMMMMMMMMMWKo'.:k0000000x,.lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "M0'.o00K0Ol.,OWMMMMMMMMMM0,.oO0Kx.,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk;;ccccc:;,,oXMMMMMMMMNOc..:x0K00000Ol''xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MNl.,k000K0o''l0WMMMMMMMXc.l000KO,.xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl.l0KK0K00O:.dWMMMMW0o,.,lk0000000kl,'lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMKc.:OK0000kc..c0WMMMMMk.,kK00KO,.xMMMMMMMMMMMMMMMMMMMMMWWMMMMMMXc.l0K000000l.oWMWKd;.'cx0K00000ko;';dKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMXl.;k000000kc,':xKWMWd.;OK00Kk,.kMMMMMMMMMMMMMMMMMMMNOlcOWMMMMK,'xK0000KKk,'x0d:,,:dO000000Od:',lONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMNd..lO000000Oxc,,:ld:.:0K00Kk'.OMMMMMMMMMMMMMMMMMMKc,;':KMMMMk':OK0000Okc..,,;lxO0000K00xc'.;xXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMWO;.'oO00K00K0Odc,...:OK00Kk'.OWWWNXKKNMMMMMMMMMXc.cOo',dO0x;,x0K0K00xo::lxO0KK00000kl,';o0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMNx,.'oO000K00000Oxdk0K00Kk;.,:::::,.cXMMMMMMMM0'.o00d,.',,:x0000000000000K00000kl,';o0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMXx:.'cdO0K000000000K0000kdooodxOo.'0MMMMMMMMK;.l0K00OkOO000K000000000000KOdc;';oONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMW0o,.'cdO0K00000000000000000KO:.:XMMMMMMMMNo..x000000000000000000000kdc'';o0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMNkl;',:ok00K0000000KKK00Od; .xWMMMMMMMMMXl.'oO0000000000K000kxdc;',cd0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMWKkl:;;:oO000K0xoooc;'',lOWMMMMMMMMMMMNk;.,cdO00000000xc,'',:oONWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMWXd.,kK00KO:.'codk0NMMMMMMMMMMMMMMMMNOo,.,x0K0000d''oO0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMXOxdddxxk0KNWMMK;'xK00K0:.lNMMMMMMMMMMMMMMMMMMMMMMMNo.:O00000x''kWMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMNl.',,''....':okO:.o000K0l.:XMMMMMMMMMMMMMMMMMMMMMMWk',kK0000x,'xWMMMWNKOxddollc::::cloxOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMK,.cllodoolc;'.... ;OK000d.,0MMMWNNXK0000KKKXXNWMMWk,,x00000o.,kN0xl:;,,'..'',,;;;;;,,'',,;dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMM0'.c:,';loddddoc;. .cOKK0x'.cxoc;,''.....''''',;coc.'d0000Oc.;xd;..',;clooodddoolcc:::cloc.'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMM0'.ldl;..':odddddl,..:do:,. ...',;;:cccllcccc:;,'.. ..;okd;.,;'.,coddddddol:;,'''',,;;:coc.;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMK,.:dddl;...codddoc.  ...,:clodddddddddddddddddddolc;'.... ..':oddddddol;'...,:looddddddl'.oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMX: ,oddddl,..,loc'...;clodddddddddddddddddddddddddddddoc,. .:odddddooc,...,coddddddddddl,.cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMWd..cdddddo:. ....;loddddddddddddddddddddddddddddddddddddc:lddddddl;...,codddddddddddoc..lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMX:.'lddddddc. .,ldddddddddddddddddddddddddddddddddddddddddddddddl'.';loddddddddddddo;. ,dO00KNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMKc.'lddddo;..codddddddddddddddddddddddddddddddddddddddddddddddl,,lodddddddddddddoc.........'',,;:ldOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMNd'.;loo;.'ldddddddddddddddddddddddddddddddddddddddddddddddddl:ldddddddddddddol,..:ooooollc::;;,'...,cd0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMXx:''. .cddddddddddddddddddddddddddddddddddddddddddddddddddooodddddddddddoc,..,lddddddddddddddoolc;'..;lOXWMMMMMMMMMMMMMMMMMMMMNKKXWMMMMMM"
echo "MMMMMMMMMMMMMMWKl. ;oddolllodddddddddddddddddooloodddddddddddddddddddddddoooodddddol:...,codddddddddddddddddddddoc;'.,ckXWMMMMMMMMMMMMMMNOl,..'c0WMMMM"
echo "MMMMMMMMMMMMMMMWx..loloo;..,lddddddddddddddocc:,.';loddddddddddddddddddddl,.'::;,,...';loddddddddddddddddddddddddddol:'.'l0WMMMMMMMMMWKx;..,cc;.'kWMMM"
echo "MMMMMMMMMMMMMMMXc ,l,;ONk.  ;oddddddddddddl,c0NO,  .:odddddddddddddddddddl.  ....',:loddddddddddddddddddddddddddddddddol;..:OWMMMWN0d;..':loddd:.;KMMM"
echo "MMMMMMMMMMMMMMMK,.:;  ';'   ;odddddddddddo; .oxl.   .:oddddddddddddddddddl. .;oooddddddddddddddddddddddddddddddddddddddddo:..ckxo:'...;loddddddc..kMMM"
echo "MMMMMMMMMMMMMMMO..c;       .cddddddddddddl.          'oddddddddddddddddddc. .cdddddddddddddddddddddddddddddddddddddddddddddo;.  ..,:loddddodddo; '0MMM"
echo "MMMMMMMMMMMMMMMk..lc.     'coddddddddddddl'          ;odddddddddddddddddo;. 'lddddddddddddddddddddddddddddddddddddddddddddddo:. .ldddddddddddo:..oNMMM"
echo "MMMMMMMMMMMMMMWd.'odl;'';coddddddddddddddo;.        'lddddddddddddddddddl...;odddddddddddddddddddddddddddddddddddddddddddddddo:. 'ldddddddddo;..lXMMMM"
echo "MMMMMMMMMMMMMMK:.:ddddddddddddddddddddddddo:'.....,:oddddddddddddddddddo,..:ldddddddddddddddddddddddddddddddddddddddddddddddddo:. ,odddddol;..,xNMMMMM"
echo "MMMMMMMMMMMMMK:.,odddddddddddddddddddddddddddoolooddddddddddddddddddddo:..codddddddddddddddddddddddddddddddddddddddddddddddddddo, .cddol:'..,dXMMMMMMM"
echo "MMMMMMMMMMMM0; .ldddddoddddddddddddddddddddddddddddddddddddddddddddddo;..:odddddddddddddddddddddddddddddddddddddddddddddddddddddl. .''..';oONMMMMMMMMM"
echo "MMMMMMMMMMMK; .cdo:;,''',;:lddddddddddddddddddddddddddddddddddddddddl,..coddddddddddddddddddddddddddddddddddddddddddddddddddddddo;  'cdOXWMMMMMMMMMMMM"
echo "MMMMMMMMMMXc .cdl'.:oc'.....;loddddddddddddddddddddddddddddddddddol:..,ldddddddddddddddddddddddddddddddddddddddddddddddddddddddddc..dWMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMO. ;odc.'oxo;,,'''.'lddddddddddddddddddddddddddddddddoc,..'coddddddddddddddddddddddddddddddddddddddddddddddddddddddddddo. :XMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMO' ,odo;..',,,,,'...cdddddddddddddddddddddddddddolc;'. .,coddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddo' ;KMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMNo. ;odo:..........:odddddddddddddddddddddoc::;,...   .:oddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddo, ;KMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMNx'.'lddl:,'...,:ldddddddddddddddddddddo:.......... .cddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddo; ;KMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMWKl..':loddoooddddddddddddddddddddddoc'. .'','....;ldddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddo, :XMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMWKd;..';clooddddddddddddddddoolc;,.  ..'.....';ldddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddl..dWMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMN0dc,....',;;;::;;;;,,''.....',:,. ....,:loddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd:.'0MMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMWNKkdl:;,,,,,,,,. .;:cloxOKXXO:..clodddddddddddoodddddddddddddddddddddddddddddddddddddddddddddddddddddddddddl'.lNMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNNWWK:'xKXXXXXNWWNXk''lddddddddddddo:;oddddddddddddoodddddddddddddddddddddddddddddddddddddddddddo;.'OMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo.cKXXXXXXXWWNXO,.cddddddddddddc',oddddddddddddc,coddddddddddddddddddddddddddddoddddddddddddc..xWMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:.oKXXXXXXNWWNXx. .,coodddddddo,.:ddddddddddddo,.;dddddddddddddddddddddddddddoccoddddddddddd:.;KMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKl''cOKXXXXXNWNXO;..'. ..,;clooo:.'oddddddddddddl..:dddddddddddddddddddddddddddl',oddddddddddd:.cNMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO';dl::coxkO0Okd;..lo'.,lc;'......:ddddddddddddo, .ldddddddddddddddddddddddddddl.'oddddddddddo,.oWMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkc;:lcc::::cc::. ,l;.cXMMWX0xc. 'lddddddddddddc. ,ooddddddddddddddddddooooolcc;..cddddddddddo'.xWMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOo;.';:;,;;;;,;c,.cXMMMMMMWk..:ddddddddddddl'  .''',,',,,,,,,,,,''''.......;:'.'odddddddddc.'OMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc.''..':cloc'.cXMMMMMMMK, ,odddddddddddo;..dOOkxdollcc::;. ..''',,;;'.'kNW0,.;odddddddo,.cXMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;.,:loddo:..oXMMMMMMMWx..cdddddddddddo;..kWMMMMMMMMMMMWNc 'odddddl,.:0WMMWx..:odddddo;..OMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl.;odol:'.,kWMMMMMMMMNl.'oddddddddool,.'kWMMMMMMMMMMMMMWo .ldooc,.;xNMMMMMNd..,codol, .dWMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0;..'...:xXMMMMMMMMMMNl.'ldddddol:'...c0WMMMMMMMMMMMMMMMO' .,'',ckNMMMMMMMMWk;.......,xNMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOxddkKWMMMMMMMMMMMMMO,..;::;,.. .':OWMMMMMMMMMMMMMMMMMW0dooxOXWMMMMMMMMMMMMNOdolodONWMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd:,...',cdKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"